### ISSUE TITLE
camera view turned into black screen after a few rounder of dissmiss -> reset -> scan again

### ISSUE THREAD

**Issue by jenlai1345** [hyperoslo/BarcodeScanner#100]
Hi,

I'm experiencing this issue with v4.1.0.

The camera turned completely black (however, the white rectangle focus view is still animating) after a few scans, or even if you don't scan any bar code, just dismiss and present the controller for a couple time, this also happens. 
I had to force quit the app in order to quit the scanner mode.

Thank you!

**Comment by vadymmarkov** [comment]
@jenlai1345 Please test in v4.1.2 and let us know if you still experience this problem.

**Comment by vadymmarkov** [comment]
Closing this issue, but let us know if it still doesn't work for you @jenlai1345
