### ISSUE TITLE
100% cpu usage after scanning bar code

### ISSUE THREAD

**Issue by klinkert0728** [hyperoslo/BarcodeScanner#103]
Hey i was using your library (btw is awesome), and i found an issue with the cpu usage just after i scan a barcode. Running the time profile i was able to found that the issue is in the barcode.

<img width="464" alt="screen shot 2018-03-13 at 16 05 43" src="https://user-images.githubusercontent.com/6820828/37370984-e8eded7c-26db-11e8-86a8-22e190ad8432.png">
<img width="706" alt="screen shot 2018-03-13 at 16 04 23" src="https://user-images.githubusercontent.com/6820828/37370985-e9075258-26db-11e8-8131-dd8df43acef6.png">

**Comment by vadymmarkov** [comment]
Hey @klinkert0728. I've just tested the demo app and wasn't able to re-produce it. Do you use the last version of BarcodeScanner? If so, can you point to the line of code in the library that causes this?

**Comment by klinkert0728** [comment]
hey @vadymmarkov  thanks in advance for the quickly replay. 
i'm using version  2.1.2  since the code is still running in swift 3

i saved the logs from the profile since i was not able to find the exact line, let me know if that helps


[barcode.trace.zip](https://github.com/hyperoslo/BarcodeScanner/files/1808777/barcode.trace.zip)

**Comment by vadymmarkov** [comment]
We found potential reason for this problem and it should be fixed starting from version 4. But yes, it's in Swift 4.

**Comment by klinkert0728** [comment]
oh can you point me to the solution i can try to make it work for swift 3?

**Comment by vadymmarkov** [comment]
As I remember it was about calling `captureSession.stopRunning()` at some point. Can you post your code to see how you present/dismiss barcode scanner controller?

**Comment by klinkert0728** [comment]
private func presentBarCodeScanner() {
        
        if UIImagePickerController.isSourceTypeAvailable(UIImagePickerControllerSourceType.camera) {
            let scanViewController = BarcodeScannerController()
            scanViewController.codeDelegate         = self
            scanViewController.dismissalDelegate    = self
            scanViewController.errorDelegate        = self
            self.container?.present(scanViewController, animated: true, completion: nil)
        }else {
            let alertController = UIAlertController.getAlertView(title: "This device doesn't have camera", message: nil, noopTitle: "OK")
            self.container?.present(alertController, animated: true, completion: nil)
            
            return
        }
    }
    
    // MARK: - scan view controller
 
    
    func barcodeScanner(_ controller: BarcodeScannerController, didCaptureCode code: String, type: String) {
        controller.dismiss(animated: true, completion: nil)
        subjectTextField?.text = code
        
    }
    
    func barcodeScanner(_ controller: BarcodeScannerController, didReceiveError error: Error) {
        print(error.localizedDescription)
    }
    
    func barcodeScannerDidDismiss(_ controller: BarcodeScannerController) {
        controller.dismiss(animated: true, completion: nil)
    }

**Comment by vadymmarkov** [comment]
Try to add this in BarcodeScannerController:
```swift
deinit {
    stopCapturing()
    NotificationCenter.default.removeObserver(self)
}
```

**Comment by klinkert0728** [comment]
i did this, but did not work.
  
    deinit {
       captureSession.stopRunning()
       NotificationCenter.default.removeObserver(self)
     }

**Comment by vadymmarkov** [comment]
Ok, try to call `controller.resetWithError()` before you do `controller.dismiss(animated: true, completion: nil)`?

**Comment by vadymmarkov** [comment]
Ok, running out of ideas here, but try to remove these three lines:
```swift
if whenProcessing {
   self.status = Status(state: .processing)
}
```
from https://github.com/hyperoslo/BarcodeScanner/blob/2.1.2/Sources/BarcodeScannerController.swift#L387

**Comment by klinkert0728** [comment]
it works. thank you very much for your help man. i really appreciate it

**Comment by mmatheusmmiguel** [comment]
Hey guys,
This solves the problem, but removes the animation. Is there no other way?

**Comment by vadymmarkov** [comment]
You don't really need that animation when you dismiss controller, do you?

**Comment by mmatheusmmiguel** [comment]
@vadymmarkov The animation that appears is product search and / or product not found.
