### ISSUE TITLE
Works with EAN13 Barcode

### ISSUE THREAD

**Issue by mmatheusmmiguel** [hyperoslo/BarcodeScanner#104]
Hello guys,

I would like to know if it is possible to check EAN13 format barcodes with this library?

Thanks,

**Comment by vadymmarkov** [comment]
Hi @mmatheusmmiguel, yes, it should work with EAN13 format.

**Comment by mmatheusmmiguel** [comment]
Hi @vadymmarkov,
Thanks for answering my last question. Would you like to know how to do the manual installation? I played in my project, but how can I reference it in the code?

**Comment by vadymmarkov** [comment]
@mmatheusmmiguel Check Readme to see how to add new metadata object type https://github.com/hyperoslo/BarcodeScanner#customization. This is a list of codes used by default https://github.com/hyperoslo/BarcodeScanner/blob/master/Sources/Extensions/AVMetadataObject%2BExtensions.swift

**Comment by mmatheusmmiguel** [comment]
Hi @vadymmarkov ,

I have doubt in manually installing the library in my project, I put the Sources and Images files in my project only?

**Comment by vadymmarkov** [comment]
Yes, as it says in the README, it should be enough to download and drop Sources and Images folders in your project.
