### ISSUE TITLE
Using 99% of processor when opening Camera after Scan

### ISSUE THREAD

**Issue by NdriqimHaxhaj** [hyperoslo/BarcodeScanner#105]
If you push a new ViewController which uses AVFoundation to take pictures or videos, this library makes an enormous use of processor on background (99% on iPhone 7 Plus). Please provide a way to stop capturing or processing after a new ViewController is pushed.

**Comment by vadymmarkov** [comment]
Hi @NdriqimHaxhaj, do you use the last version of BarcodeScanner?

**Comment by NdriqimHaxhaj** [comment]
Hi @vadymmarkov, I’ve installed the latest version via pods. Maybe it should be something else.

**Comment by mmatheusmmiguel** [comment]
@NdriqimHaxhaj Did this solve the problem?

**Comment by NdriqimHaxhaj** [comment]
@mmatheusmmiguel Not actually. Tried to load the Camera without the barcode scanner on Navigation Controller Stack and it consumes 0% from processor. I need to keep the barcode on Navigation Controller Stack for various reasons of my application. The problem appears when I open a new View Controller which uses AVFoundation on top of barcode scanner.

**Comment by vadymmarkov** [comment]
@NdriqimHaxhaj Don't call `reset` before you push new view controller if you do so, then it's not gonna start capturing. Later you can call `reset(animated: false)` when you go back to barcode scanner view controller.

**Comment by NdriqimHaxhaj** [comment]
All I do when the capture is done is this: 

1. Create the Camera View Controller
2. Push it from Barcode View Controller

`func scanner(_ controller: BarcodeScannerViewController, didCaptureCode code: String, type: String {
        let deviceCameraController = DeviceCameraViewController.create()
        controller.push(deviceCameraController)
    }`

**Comment by vadymmarkov** [comment]
Ok, try calling `controller.reset(animated: false)` before you push new view controller. Alternatively, you can set `controller.isOneTimeSearch = false` when you configure your barcode scanner controller.

**Comment by NdriqimHaxhaj** [comment]
The `controller.reset(animated: false)` did the trick. I was using just `controller.reset()` instead, which gave me some screen freezings. I need it to be oneTimeSearch in my case. Thank you a lot @vadymmarkov
