### ISSUE TITLE
messageViewController.textLabel.text

### ISSUE THREAD

**Issue by ChrisSwipecart** [hyperoslo/BarcodeScanner#107]
Cannot set the text. 
When I set the text, the default text is still shown, not my string.
But if I go into the localised strings, I can change the English string there and it works. Localisations seem to be overriding it.

**Comment by sagarnatekar** [comment]
@ChrisSwipecart - The documentation needs to be updated, but the way to set custom messages is via the `StateMessageProvider`. e.g: try `viewController.messageViewController.messages.scanningText = "Barcode Scanner"` in the example project and you should see it updated at runtime.
