### ISSUE TITLE
Cocoapods not support?

### ISSUE THREAD

**Issue by xuanzi23** [hyperoslo/BarcodeScanner#11]
When I trying to install, it show [!] Unable to find a specification for `BarcodeScanner`

**Comment by onmyway133** [comment]
@xuanzi23 can you try

```
pod repo update
```

or

```
pod repo remove master
pod setup
```

then `pod install` again?

**Comment by xuanzi23** [comment]
@onmyway133 is working great now!
For the Customization, where should I edit the code?

**Comment by onmyway133** [comment]
@xuanzi23 great to hear that. For the customization, you should do that before you use BarcodeScanner, `appDidLaunch` event maybe a good place
