### ISSUE TITLE
Does this barcode wrapper work with +2 and +5 UPC-A codes?

### ISSUE THREAD

**Issue by ethanwa** [hyperoslo/BarcodeScanner#115]
If not, I'd like to request this as a feature **please**. Thank you! It's critical for my application and what I am using now is outdated. Thanks!

**Comment by vadymmarkov** [comment]
There is a list of `AVCaptureMetadataOutput` metadata object types included by default: https://github.com/hyperoslo/BarcodeScanner/blob/master/Sources/Extensions/AVMetadataObject%2BExtensions.swift#L7. Check https://developer.apple.com/documentation/avfoundation/avcapturemetadataoutput to know if codes you're interested in are supported.

**Comment by ethanwa** [comment]
Unfortunately +2 and +5 is not supported by Apple’s built-in stuff. I am currently using a very outdated ZBar implementation that includes +2 and +5 scanning.
