### ISSUE TITLE
Error Message not displaying

### ISSUE THREAD

**Issue by burf2000** [hyperoslo/BarcodeScanner#116]
Epic framework!  
So I am expecting when I detect a code, and I use the following command, a red product not found message should appear as shown in the pictures. (as the default tint is red)

self.resetWithError(message: "Product not found")

This line is called on the delegate but no message displayed, it just resets the screen

iOS 11.4, latest released xcode

**Comment by burf2000** [comment]
Solved it looking at the demo app
DispatchQueue.main.asyncAfter(deadline: .now() + 2.0) {
                controller.resetWithError()
            }

**Comment by MohanRamanathan** [comment]
I too struck at this. This helped me to fix the same issue. Thanks. If possible add this line in the description, will be useful.

**Comment by Go-Pomegranate** [comment]
It's still not working for me, red  error barcode just blinking and dissapear . Please show me the code where I can change that behaviour, I tried with BarcodeScannerViewController but failed to figure it out !

**Comment by Go-Pomegranate** [comment]
Changed iOS version to 11.4 and it's working now. Before I had version 12 , anyone knows what happend and how to make it work on iOS 12?

**Comment by Go-Pomegranate** [comment]
Ok after some hours of readings on GCD and multithreading I found this line od code:

### **In MessageViewController ** 

if #available(iOS 11.0, *) {
            constraints += [
                imageView.leadingAnchor.constraint(
                    equalTo: view.safeAreaLayoutGuide.leadingAnchor,
                    constant: padding
                ),
                textLabel.trailingAnchor.constraint(
                    equalTo: view.safeAreaLayoutGuide.trailingAnchor,
                    constant: -padding
                )
            ]
        } else {
            constraints += [
                imageView.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: padding),
                textLabel.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -padding)
            ]
        }

Change version to 12.0 and everything will be fine.

Like this: 

if #available(iOS 12.0, *) { etc.. code here


Hope i helped :)
