### ISSUE TITLE
Disable Search For products?

### ISSUE THREAD

**Issue by hadwanihardik** [hyperoslo/BarcodeScanner#122]
Can we disable product search. As I just want barcode reading.

**Comment by tushar666** [comment]
Yes just Dismiss or PopToRootVC, once u got code within "didCaptureCode" as below

func scanner(_ controller: BarcodeScannerViewController, didCaptureCode code: String, type: String) {
    print("Code captured was --> ", code)
    controller.dismiss(animated: true, completion: nil)
  }

**Comment by michaelbina** [comment]
@tushar666 I currently am doing that but it the product search VC loads anyway and I can't dismiss it, in code or without he close button.  The scannerDidDismiss function is called but the product search screen stays up anyway.  I'm not sure what's going on.  any help?
