### ISSUE TITLE
Bar Code Reader Meta Data (Only bar code)

### ISSUE THREAD

**Issue by aabantariqmurtaza** [hyperoslo/BarcodeScanner#128]
I am working in swift 4.
I am unable to set bar code meta data.
I want my 'BarCodeReader' only to work with barcodes, no other type like QR etc.

unable to translate below line to swift 4.

viewController.metadata.append(AVMetadataObject.ObjectType.qr)

Many thanks,
Aaban.

**Comment by aabantariqmurtaza** [comment]
any help on it.

**Comment by oaleeapp** [comment]
Did you `import AVFoundation`?
