### ISSUE TITLE
Swift 4.2 Incompatible

### ISSUE THREAD

**Issue by JLamkin** [hyperoslo/BarcodeScanner#131]
Release 4.1.3 has build errors in xCode 10 using Swift 4.2. Is there a plan to update to make it Swift 4.2 compatible?

**Comment by christianneil** [comment]
@JLamkin a Pull Request (#114) is already pending and is just awaiting approval for merging.

In the meantime, if for some reason you really need the update now, consider installing the Pod from the updated [fork](https://github.com/shaqaruden/BarcodeScanner/):

**Podfile**
```podfile
pod 'BarcodeScanner', :git => 'https://github.com/shaqaruden/BarcodeScanner.git'
```

**Comment by JLamkin** [comment]
Do we know when this will be merged?

**Comment by christianneil** [comment]
@JLamkin I'm hoping it will come anytime soon. But since there doesn't seem to be too much activity in this repo recently, I somehow think it could take a while. *(There are actually 2 pull requests for a Swift 4.2 fix now.)*

**Comment by casey55** [comment]
Any update on this?

**Comment by musabeni** [comment]
waiting for update.....

**Comment by colealanroberts** [comment]
What's the status of this?

**Comment by itaispector** [comment]
> @JLamkin a Pull Request (#114) is already pending and is just awaiting approval for merging.
> 
> In the meantime, if for some reason you really need the update now, consider installing the Pod from the updated [fork](https://github.com/shaqaruden/BarcodeScanner/):
> 
> **Podfile**
> 
> ```
> pod 'BarcodeScanner', :git => 'https://github.com/shaqaruden/BarcodeScanner.git'
> ```

You're a lifesaver

**Comment by Obbut** [comment]
There is no need to use a fork. You can also place this in your Podfile:

```ruby
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'BarcodeScanner'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.1'
            end
        end
    end
end
```

**Comment by jonathanfoster** [comment]
@shaqaruden, @vadymmarkov: Any update on PR #114? Last I see is a failed CI build, `TorchMode.swift` and `NSLayoutConstraint+Extensions.swift` failed to compile. https://travis-ci.org/hyperoslo/BarcodeScanner/builds/399219803?utm_source=github_status&utm_medium=notification

**Comment by VinayGTHub** [comment]
Is there any update to support Swift 4.2

**Comment by shaqaruden** [comment]
PR#114 is now passing travis

**Comment by Edwin97** [comment]
Any update on this?

**Comment by shaqaruden** [comment]
My PR [#114](https://github.com/hyperoslo/BarcodeScanner/pull/114) is passing travis and gets Swift 4.2 support. Just waiting for it to get merged now. Been waiting a while though

**Comment by mtet88** [comment]
Any update on this?

**Comment by shaqaruden** [comment]
@mtet88 still waiting on this to be merged.

**Comment by shaqaruden** [comment]
I have emailed asking to get PR #114 to be merged.
