### ISSUE TITLE
delete messageViewController

### ISSUE THREAD

**Issue by alaaosman20** [hyperoslo/BarcodeScanner#136]
hello,
is there a way to delete the messageViewController from below the barcode camera,
see image below:

![examplescanning](https://user-images.githubusercontent.com/17074611/46808438-03000200-cd75-11e8-9965-8a15e6fcab84.png)

 I tried:
 `barcodeScannerViewController.messageViewController.view.isHidden = true`
but this will only leave it blank.
is there a way delete it completely or at least change its height?
thank you,

**Comment by jonathanfoster** [comment]
I tried hiding the barcode image and message label, but these are the same views used during processing so subsequent messages aren't displayed either. The entire messaging view controller could use more customization and extensibility. Here's what I'd like to see:

* Hide footer - no blank space where footer used to exist, no impact in subsequent states
* Hide footer image - footer label expands to fill space
* Hide footer label - no impact in subsequent states

I'm willing to work on a PR if this is something others are interested in as well (vote with 👍).
