### ISSUE TITLE
Set scanning to only happen in the box

### ISSUE THREAD

**Issue by AlexanderHearX** [hyperoslo/BarcodeScanner#141]
Currently the barcode is processed anywhere on the screen? Is it possible to only have the scanning be within the box in the middle?

**Comment by Steven4294** [comment]
I'm not seeing the barcode being processed unless its wthin the box

**Comment by Sopheak0** [comment]
@AlexanderHearX  i got the same issue

**Comment by QaiserAbbas** [comment]
Can we make it. scanning happen anywhere on the screen?

**Comment by 3lvis** [comment]
https://github.com/hyperoslo/BarcodeScanner/issues/187
