### ISSUE TITLE
Disable animation while processing

### ISSUE THREAD

**Issue by jonathanfoster** [hyperoslo/BarcodeScanner#143]
Is there anyway to disable the spinner animation while processing? The animation doesn't fit with the existing UX/UI of my app.

**Comment by n9lvc5** [comment]
I'm trying to figure that one out myself.

**Comment by n9lvc5** [comment]
Got it:
At the end of BarcodeScannerViewController.swft: 

 codeDelegate?.scanner(self, didCaptureCode: code, type: rawType)
     controller.dismiss(animated: true, completion: nil) <-- Add in this line
    //animateFlash(whenProcessing: isOneTimeSearch) <-- Gray out this line
