### ISSUE TITLE
Direct CameraViewController usage

### ISSUE THREAD

**Issue by ermik** [hyperoslo/BarcodeScanner#145]
I've tried to work with `CameraViewController` directly and it seems that some fields — e.g. `metadata` are not available unless it is instantiated by the `BarcodeScannerViewController`. Is there a way to use just the camera controller?

**Comment by prashantbelani** [comment]
Same issue I'm facing, any solution? @ermik

**Comment by ermik** [comment]
@prashantbelani I have looked at the code and wrote a simple VC myself; this was helpful: https://github.com/MxABC/swiftScan/blob/master/Source/LBXScanViewController.swift
