### ISSUE TITLE
Is this support swift 3.0?

### ISSUE THREAD

**Issue by oniikal3** [hyperoslo/BarcodeScanner#15]
My project already up to swift 3.0. except this library. Do you guys update it?

**Comment by zenangst** [comment]
Like I stated in the PR for `swift-3`, try modifying your `Podfile` :)

#14

**Comment by vadymmarkov** [comment]
@oniikal3 Version 2.0 is out https://github.com/hyperoslo/BarcodeScanner/releases/tag/2.0.0
