### ISSUE TITLE
Has this project been orphaned? It doesn't work with recent Swift versions

### ISSUE THREAD

**Issue by cbnewham** [hyperoslo/BarcodeScanner#156]
Amongst a whole host of errors:  UIControlState() has been renamed to UIControl.State

Is there an intention to update this project to the latest version of Swift?

**Comment by Kalvin126** [comment]
There have been multiple PRs to update the project to Swift 4.2 and 5. No reviews or comments on them though.

**Comment by aldoblack** [comment]
Click on 'Fix' button and XCode will fix them automatically and it will compile. I am using it on Swift 5.
