### ISSUE TITLE
Corner Radius for barcode box animation

### ISSUE THREAD

**Issue by PauloxD** [hyperoslo/BarcodeScanner#16]
Just thought I'd make you aware, that for some reason the square that is used for the loading animation does not display it's corner radius correctly. It is no big deal, and is purely cosmetic but I thought I'd highlight it. I have tried increasing the corner radius myself, but it does not seem to have any effect.

**Comment by zenangst** [comment]
Hey @PauloxD, thanks for bringing this up, I launched the example application on my phone to investigate what was going on here but I don't think I'm seeing what you are seeing.

This is what it looks like for me:

![img_0091](https://cloud.githubusercontent.com/assets/57446/19531403/d5ec1130-9637-11e6-9326-526ee9767015.PNG)

**Comment by PauloxD** [comment]
Thanks for getting back to me. The box in question is the one that displays after the barcode has been scanned. The one that rotates around 90 degrees whilst it is searching for the barcode. Sorry that I didn't clarify :)

**Comment by vadymmarkov** [comment]
It should be fixed in v4.0.0.
