### ISSUE TITLE
Swift 5 support ?

### ISSUE THREAD

**Issue by ismailtosun** [hyperoslo/BarcodeScanner#160]

**Comment by zzarizz** [comment]
or even SwiftUI, that would be awesome

**Comment by CLoutas** [comment]
I am currently using BarcodeScanner in a SwiftUI project and haven't had any issues so far.

**Comment by ecamodeo** [comment]
@CLoutas  I am trying to use BarcodeScanner in a SwiftUI project.  I currently have it displaying using a wrapper but my delegates (code, error, dismiss) never run.  Any advice you can give I would be greatful!

**Comment by CLoutas** [comment]
@ecamodeo are you using a Coordinator object as your delegates? If not, have a look at this: https://www.hackingwithswift.com/books/ios-swiftui/using-coordinators-to-manage-swiftui-view-controllers

**Comment by ecamodeo** [comment]
@CLoutas I appreciate the time and apologize as I am kind of new to this whole thing but here is what I have for my Coordinator.
`class Coordinator: NSObject, BarcodeScannerCodeDelegate, BarcodeScannerErrorDelegate, BarcodeScannerDismissalDelegate {
    
    func scanner(_ controller: BarcodeScannerViewController, didReceiveError error: Error) {
      print(error)
    }
    
    private func makeBarcodeScannerViewController() -> BarcodeScannerViewController {
      let viewController = BarcodeScannerViewController()
      viewController.codeDelegate = self
      viewController.errorDelegate = self
      viewController.dismissalDelegate = self
      return viewController
    }
    
    func scanner(_ controller: BarcodeScannerViewController, didCaptureCode code: String, type: String) {
      

        DispatchQueue.main.asyncAfter(deadline: .now() + 2.0) {
            print("Barcode Data: \(code)")
            controller.dismiss(animated: true, completion: nil)
        }
//      attendees.append(code)
//      print("Scanned Attendees: \(self.scannedAttendees)")
//      let index = self.find(value: code, in: self.scannedAttendees)
//
//      DispatchQueue.main.asyncAfter(deadline: .now() + 2.0) {
//
//          if index != nil {
//              controller.messageViewController.errorTintColor = UIColor.orange
//              controller.resetWithError(message: "Student Already Scanned!")
//              print("Student already counted. No count change.")
//          } else {
//
//              for student in self.students {
//                  if code == student.studentNumber {
//                      self.incrementHouseCount(eventID: self.selectedEventID!, house: student.house!.lowercased(), attendee: student.studentNumber!)
//                      controller.messageViewController.errorTintColor = .green
//                      controller.resetWithError(message: "Student Found!\n\(student.firstName!) \(student.lastName!)")
//                      print("New count added to event.")
//                  }
//              }
//          }
//      }
    }

    func scannerDidDismiss(_ controller: BarcodeScannerViewController) {
      print("Dismissed!")
      controller.dismiss(animated: true, completion: nil)
    }
}`

**Comment by CLoutas** [comment]
**I'm having two objects, first the actual view (not full code, but should have everything you need):**

 struct ScannerView: UIViewControllerRepresentable {

    func makeCoordinator() -> ScannerViewCoordinator {
        ScannerViewCoordinator(self)
    }
    
    func makeUIViewController(context: UIViewControllerRepresentableContext<ScannerView>) -> BarcodeScannerViewController {
        return createAndConfigureScanner(context: context)
    }
    
    func updateUIViewController(_ uiViewController: BarcodeScannerViewController, context: UIViewControllerRepresentableContext<ScannerView>) {
            uiViewController.reset(animated: false)
      }

     private func createAndConfigureScanner(context: UIViewControllerRepresentableContext<ScannerView>) -> BarcodeScannerViewController {
        let barcodeVC = BarcodeScannerViewController()
        barcodeVC.codeDelegate = context.coordinator
        barcodeVC.errorDelegate = context.coordinator
        
        return barcodeVC
    }


**And here is my coordinator (again, not full code):**

class ScannerViewCoordinator: BarcodeScannerCodeDelegate, BarcodeScannerErrorDelegate {
    
    private var scannerView: ScannerView
    
    init(_ scannerView: ScannerView) {
        self.scannerView = scannerView
    }
    
    func scanner(_ controller: BarcodeScannerViewController, didCaptureCode code: String, type: String) {
        guard let scanItem = ScanParser().parse(content: code) else {
            controller.reset(animated: true)
            return
        }
        
        // Update the view with the scan result.
        self.scannerView.scanResult = scanItem
    }
    
    func scanner(_ controller: BarcodeScannerViewController, didReceiveError error: Error) {
        self.scannerView.scanFailed = true
    }
    
}

**Comment by ecamodeo** [comment]
@CLoutas Thank you so much for your help and time!  Works great.

**Comment by CLoutas** [comment]
Perfect, happy to hear that helped! You’re welcome 🙂
