### ISSUE TITLE
No such module 'BarcodeScanner' when compile project 

### ISSUE THREAD

**Issue by mdemori** [hyperoslo/BarcodeScanner#166]
Hello, 

I'm unable to compile my test project using the pod install. When I try to do
Import BarcodeScanner, i receive an error "No such module 'BarcodeScanner'

my podfile is as below:

use_frameworks!
platform :ios, '13.0'
pod 'BarcodeScanner'
target 'TestBarcode'

how can I solve this problem?

Thank you

**Comment by mdemori** [comment]
after some digging around i discover that the problem is related to the fact that I use the project instead the workspace inside xCode. Opening the workspace solve all problems.

**Comment by aldoblack** [comment]
> after some digging around i discover that the problem is related to the fact that I use the project instead the workspace inside xCode. Opening the workspace solve all problems.

What version of Swift are you using? I just tried to compile it on Cataline 10.15.4 and it fails on Swift 4, 4.3 and 5.
