### ISSUE TITLE
Add support for Swift Package Manager

### ISSUE THREAD

**Issue by g30r93g** [hyperoslo/BarcodeScanner#168]

**Comment by furiosFast** [comment]
any news?

**Comment by 3lvis** [comment]
Hi, this library is in maintenance mode, no further work is planned but if you are up for adding it I'll be happy to review it and merge it :)

**Comment by furiosFast** [comment]
something like this:

`
// swift-tools-version:5.0
// The swift-tools-version declares the minimum version of Swift required to build this package.
import PackageDescription

let package = Package(
    name: "BarcodeScanner",
    platforms: [
        .iOS(.v9)
    ],
    products: [
        .library(
            name: "BarcodeScanner", targets: ["BarcodeScanner"]),
    ],
    targets: [
        .target(
            name: "BarcodeScanner", dependencies: []),
    ]
)
`

**Comment by 3lvis** [comment]
I haven't done it before so I'm not sure what it takes :)

**Comment by EliteTechnicalCare** [comment]
> something like this:
> Package.swift
> 
> ```
> // swift-tools-version:5.0
> // The swift-tools-version declares the minimum version of Swift required to build this package.
> import PackageDescription
> 
> let package = Package(
>     name: "BarcodeScanner",
>     platforms: [
>         .iOS(.v9)
>     ],
>     products: [
>         .library(
>             name: "BarcodeScanner", targets: ["BarcodeScanner"]),
>     ],
>     targets: [
>         .target(
>             name: "BarcodeScanner", dependencies: []),
>     ]
> )
> ```

I believe this is the only thing missing. SPM support would be a great addition

**Comment by 3lvis** [comment]
@EliteTechnicalCare I'll be happy to merge it if someone makes a PR!
