### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by Mazorati** [hyperoslo/BarcodeScanner#18]
Hello!

Thanks for library!
I noticed a high load on the processor. This happens when I close the controller. 
Please check it.

Alexandr.

![2016-10-31 9 36 56](https://cloud.githubusercontent.com/assets/3396425/19846163/dbf22c3a-9f4d-11e6-9d35-b52d04fd9c58.png)

**Comment by Mazorati** [comment]
1-st option:
```
func barcodeScanner(_ controller: BarcodeScannerController, didCaptureCode code: String, type: String) {
        controller.dismiss(animated: true, completion: nil)
    }
```
causes high CPU leaks

**Comment by zenangst** [comment]
Thanks for reporting this @Mazorati, we will investigate to see if we cannot fix it.

**Comment by algrid** [comment]
Looks like retain cycle in InfoView causing infinite animation.

**Comment by zenangst** [comment]
@Mazorati I just merged @algrid's pull request, could you try with `master` now?

**Comment by zenangst** [comment]
Closing this thread because it lacks activity, feel free to re-open it if the issues still persists.
