### ISSUE TITLE
does not scan a barcode

### ISSUE THREAD

**Issue by NikolayGrishchenko** [hyperoslo/BarcodeScanner#182]
does not scan a barcode (https://prnt.sc/thzqnk), but scan QR code (https://prnt.sc/thzqyy).

please, help!

**Comment by milanpanchal** [comment]
I'm able to scan your barcode (https://prnt.sc/thzqnk). Can you please elaborate your issue in detail.

**Comment by 3lvis** [comment]
Works fine for me too, closing for lack of follow up.
