### ISSUE TITLE
Interleaved 2and5 12 Digits

### ISSUE THREAD

**Issue by avaz** [hyperoslo/BarcodeScanner#186]
Is this library compatible with the attached image barcode? It's a 2and5 interleaved of 12 digits.
![PHOTO-2020-10-15-16-47-29](https://user-images.githubusercontent.com/29484/96177249-d667bd80-0f2d-11eb-99b5-56c5b7393222.jpg)

**Comment by 3lvis** [comment]
Hi @avaz, I don't think so but feel free to double check, there should be a demo in the project.

**Comment by avaz** [comment]
Hi @3lvis 
Thanks for you reply. I tried it out and indeed it didn't work. It keeps trying to scan but don't get anything.
Is possible though a configuration make this library read this kind of barcode? Or it would require a more deep change in the library functions?

Thanks in advance.

**Comment by 3lvis** [comment]
@avaz Hi Avaz, my job is to keep the library updated. Probably, @vadymmarkov or @onmyway133 have a better overview of this. My suspicions is that this might not be the right library for what you are looking for.

**Comment by vadymmarkov** [comment]
Hi @avaz! Please check my old comment from another issue https://github.com/hyperoslo/BarcodeScanner/issues/115#issuecomment-406859344. If your type of code is supported by Apple you can add it as described in documentation https://github.com/hyperoslo/BarcodeScanner#customization

**Comment by avaz** [comment]
Seems to be indeed not supported. If anyone there knows a more updated library that supports it I will be glad in know about. Thanks.
