### ISSUE TITLE
SPM installation - Invalid Resource 'cameraRotate@3x.png' not found.

### ISSUE THREAD

**Issue by Zach-McArtor** [hyperoslo/BarcodeScanner#203]
Hello,

I have installed version 5.0.1 through SPM, but get this warning regarding a missing asset file.  

<img width="772" alt="Screen Shot 2022-02-09 at 2 11 49 PM" src="https://user-images.githubusercontent.com/93160486/153291000-194d0b07-40d6-416c-a38c-c1151e366daf.png">

**Comment by mthole** [comment]
Bump, easy fix here

**Comment by mthole** [comment]
See https://github.com/hyperoslo/BarcodeScanner/pull/206
