### ISSUE TITLE
Arabic Language Localization

### ISSUE THREAD

**Issue by fuadwaheed** [hyperoslo/BarcodeScanner#204]
How to add Arabic Language Localization?

**Comment by Firas-Shrourou** [comment]
You can localize the title and the close button

`        let viewController = BarcodeScannerViewController()
          
        viewController.headerViewController.titleLabel.text = "Page_Title_Scan_Barcode".localized
        viewController.headerViewController.closeButton.setTitle("btn_Close".localized, for: .normal)
        
        viewController.codeDelegate = self
        viewController.errorDelegate = self
        viewController.dismissalDelegate = self
        return viewController`

**Comment by 3lvis** [comment]
Looks like you got it working!
