### ISSUE TITLE
Support for EAN-13 barcodes

### ISSUE THREAD

**Issue by ismaelgobernado** [hyperoslo/BarcodeScanner#22]
Does BarcodeScanner give support for EAN-13 barcodes ?

**Comment by samaRox** [comment]
@ismaelgobernado This is my output scanning a EAN-13 barcode so i suggest it works.
![image](https://cloud.githubusercontent.com/assets/25846816/24115438/a6ac53d8-0da3-11e7-9ce9-c0736aad225f.png)

**Comment by vadymmarkov** [comment]
Seems like the issue is solved. You can also check https://github.com/hyperoslo/BarcodeScanner/issues/43 to see how to add new types of barcodes.
