### ISSUE TITLE
CloseButton position

### ISSUE THREAD

**Issue by ADevelopStudio** [hyperoslo/BarcodeScanner#23]
Hi!
is there any chance to move close button from left to right top corner?

**Comment by Metric** [comment]
Actually, for UX concerns it should be near the center bottom area, where the thumb can reach it, without stretching. I shouldn't have to use two hands to close out the scanner on an iPhone 7 or iPhone 7 Plus. 

See: http://scotthurff.com/posts/how-to-design-for-thumbs-in-the-era-of-huge-screens

**Comment by tylerwilson** [comment]
I too would prefer it in the upper right. I agree about the one-handed use-case, but short of that an option to place it on the right - which I think is more common when put in a NavBar would be great.

**Comment by vadymmarkov** [comment]
Starting from v4.0.0 you have direct access to public properties of [HeaderViewController](https://github.com/hyperoslo/BarcodeScanner/blob/master/Sources/Controllers/HeaderViewController.swift#L16), so you can for example add right button item and remove the left one. It is also possible set `BarcodeScannerController` as a root view controller of `UINavigationController`, so you have full control over navigation bar.

**Comment by mr5z** [comment]
Is it possible to remove the additional controls and leave it with just the Camera screen?
