### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by sunilhts** [hyperoslo/BarcodeScanner#28]
Getting this error :::::
dyld: Library not loaded: @rpath/BarcodeScanner.framework/BarcodeScanner
  Referenced from: /var/containers/Bundle/Application/154B00B7-2208-42B6-840F-6F02FCCA5AE2/(****AppName****).app/(****AppName****)
  Reason: image not found

I'm using Xcode 8.2.1 and the barcodescanner pod version latest.....
pod installation was successful.. pod version is 1.2.0....... can you address this issue ASAP

**Comment by vadymmarkov** [comment]
@sunilhts There are multiple reasons that can cause this error, but I'm afraid non of them is actually related to `BarcodeScanner` framework. You can try clear your `DerivedData` or do `pod deintegrate && pod install` for example.

**Comment by sunilhts** [comment]
@vadymmarkov thanks for your reply.. It's working fine.. but running the code every time by clearing DerivedData or pod deintegration making me sick.. :(

**Comment by glararan** [comment]
Same issue, don't using pod. Im using Carthage. DerivedData clear didn't work for me. App is new project with included BarcodeScanner
