### ISSUE TITLE
Retrieving an UIImage, possibly with a pinch enabled window

### ISSUE THREAD

**Issue by ugur10** [hyperoslo/BarcodeScanner#34]
Great library, congrats!

How can I retrieve a UIImage, for instance a string like **r2Us1gf907** on a box.

If we can manipulate the auto focusing window to detect strings, that's awesome, but I do not know how.

If we can not do that, how can we add something like this?

And lastly, how can I retrieve the UIImage after the focus and taking the shot? 

We may have to add a camera button for it probably, since the library auto captures the barcodes by itself. 

OR 

We can make it auto capture enabled for alphanumeric strings, but I do not know how yet.

Hope to see wisdom below. 

Thanks!

**Comment by vadymmarkov** [comment]
I think it's out of scope of this library. Feel free to re-open if you want to discuss it more in details.
