### ISSUE TITLE
Interleaved 2 of 5 (ITF, from Interleaved Two of Five)

### ISSUE THREAD

**Issue by Florensvb** [hyperoslo/BarcodeScanner#36]
I need **BarcodeScanner** to add support for [Interleaved 2 of 5](https://en.wikipedia.org/wiki/Interleaved_2_of_5) because they are commonly used for airplane luggage tags.

**Comment by vadymmarkov** [comment]
Right now *BarcodeScanner* supports all the barcode types that can be natively recognised. There is a list of metadata object types used by default https://github.com/hyperoslo/BarcodeScanner/blob/master/Sources/Config.swift#L76

**Comment by georgepoenaru** [comment]
I just add PR for this.  Thank's

https://github.com/hyperoslo/BarcodeScanner/pull/38

**Comment by vadymmarkov** [comment]
The issue was solved https://github.com/hyperoslo/BarcodeScanner/pull/38
