### ISSUE TITLE
Preview flattened when in container

### ISSUE THREAD

**Issue by jeryRazakarison** [hyperoslo/BarcodeScanner#40]
Hi,

I would like to put the BarcodeScannerController inside a ContainerView (in order to have the Barcode scanner on the top half of the screen, and a tableview with the list of scanned barcode on the bottom half of the screen).

But when I tries to embed the BarcodeScannerController in a container which sizes the half of the height of the screen, the preview is flattened. Do anyone have an idea of how to fix it?

Thank you a lot,

Jery

**Comment by Metric** [comment]
This would be due line 179 in the controller: videoPreviewLayer?.videoGravity = AVLayerVideoGravityResize;

It should be: videoPreviewLayer?.videoGravity = AVLayerVideoGravityResizeAspectFill;

**Comment by jeryRazakarison** [comment]
Oh, yes! Thank you for pointing this. Do you intend to do a PR, or do you want me to do it?

**Comment by vadymmarkov** [comment]
Fixed https://github.com/hyperoslo/BarcodeScanner/pull/41
