### ISSUE TITLE
Specify barcode type configuration

### ISSUE THREAD

**Issue by jlfeck** [hyperoslo/BarcodeScanner#43]
Is it possible to specify a single barcode type to be used?

I want to allow the app only to read one barcode type.

Tks

**Comment by vadymmarkov** [comment]
@jlfeck Yes, it's possible:
```swift
BarcodeScanner.metadata = [
  AVMetadataObjectTypeUPCECode
]
```

**Comment by jlfeck** [comment]
"Issue" solved 😬!

Tks again 😛!
