### ISSUE TITLE
Force orientation and capture layer

### ISSUE THREAD

**Issue by jlfeck** [hyperoslo/BarcodeScanner#44]
Is it possible to force landscape or portrait?
Also, is it possible to specify the layer capture for barcode (as seen in the image below)?

Tks!

![example_mobile](https://user-images.githubusercontent.com/4379708/27870104-59b7487a-6178-11e7-9bc4-98e5feade89c.jpeg)

**Comment by vadymmarkov** [comment]
@jlfeck No, unfortunately we don't support this kind of customisation at the moment, but feel free to contribute if you're up for it 😉
