### ISSUE TITLE
Chinese Simplified (Zh-Hans) Localization

### ISSUE THREAD

**Issue by codwam** [hyperoslo/BarcodeScanner#53]
"SCAN_BARCODE_TITLE" = "扫描条形码";
"BUTTON_CLOSE" = "关闭";
"BUTTON_SETTINGS" = "设置";
"INFO_DESCRIPTION_TEXT" = "将条形码放置在窗口内进行扫描,将自动搜索。";
"INFO_LOADING_TITLE" = "寻找你的产品…";
"NO_PRODUCT_ERROR_TITLE" = "没有发现产品。";
"ASK_FOR_PERMISSION_TEXT" = "你必须在设置里面打开相机权限才可以扫描条码。";

Close any time.

**Comment by vadymmarkov** [comment]
@codwam That's great. Could you make a PR as well?

**Comment by codwam** [comment]
I don't known how to add localization in your project, issue just a suggestion
