### ISSUE TITLE
Info View customization

### ISSUE THREAD

**Issue by andrealufino** [hyperoslo/BarcodeScanner#54]
Hello, is there a way to customize the info view? Change the background color, hide it and other stuff like this.

**Comment by csteele86** [comment]
From what I understand, these are the only configurations/customizations available: https://github.com/hyperoslo/BarcodeScanner#customization

**Comment by vadymmarkov** [comment]
Starting from v4.0.0 you have direct access to public properties of [MessageViewController](https://github.com/hyperoslo/BarcodeScanner/blob/master/Sources/Controllers/MessageViewController.swift), so you can do something like:
```swift
let viewController = BarcodeScannerViewController()
viewController.messageViewController.textLabel.textColor = .black
```
