### ISSUE TITLE
Feature Request: More control over how messages are displayed

### ISSUE THREAD

**Issue by csteele86** [hyperoslo/BarcodeScanner#56]
Currently, only 2 lines are allotted for displaying messages, which may not work when displaying longer messages. It would also be nice to be able to adjust the line spacing as well to make longer messages a little easier to read.

**Comment by vadymmarkov** [comment]
We use the same label both for footer text and loading text. Since v4.0.0 footer text could be 2 lines max and loading/not found text is 10 lines max. Hope it solves your problem.
