### ISSUE TITLE
Change color of Navigationbar

### ISSUE THREAD

**Issue by HendrikFW** [hyperoslo/BarcodeScanner#58]
Hi,
my app uses a dark theme with an custom color UINavigationBar. Is there a way to change the color of the navigation bar which is visible while scanning?

**Comment by vadymmarkov** [comment]
@HendrikFW You can use https://github.com/hyperoslo/BarcodeScanner/blob/master/Sources/Config.swift#L10 to set a color.

**Comment by zenangst** [comment]
Seems like this is resolved, closing now 👋
