### ISSUE TITLE
Do not add subviews directly to the visual effect view itself, instead add them to the contentView

### ISSUE THREAD

**Issue by brenomorais88** [hyperoslo/BarcodeScanner#59]
I'm trying to read barcodes with the library but when I try to open the scanner with ios 11 I get this error and the app breaks:

_**Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<UILabel: 0x1014a97d0; frame = (0 0; 0 0); userInteractionEnabled = NO; layer = <_UILabelLayer: 0x1c02936a0>> has been added as a subview to <BarcodeScanner.InfoView: 0x1015780d0; baseClass = UIVisualEffectView; frame = (0 0; 0 0); layer = <CALayer: 0x1c4226100>>. Do not add subviews directly to the visual effect view itself, instead add them to the -contentView.'**_

I'm using iOS 11 Beta 4
The library version is 2.1.1

**Comment by DavidLari** [comment]
This is a duplicate of issue #46. They fixed it but I don't think the fix has been released yet.

**Comment by brenomorais88** [comment]
Is there a launch forecast?

**Comment by vadymmarkov** [comment]
2.1.2 has been released.
