### ISSUE TITLE
Swift 4

### ISSUE THREAD

**Issue by chadcummings** [hyperoslo/BarcodeScanner#62]
I've updated the BarcodeScanner Framework and the Example project to Swift 4 with Base SDK 11 and changed the deployment target to iOS 10.3 (since anything less than 10.3 has less than a 9% market share).
I've also added support for all orientations and fixed a bug where the Header would disappear if the rotation was changed.
I also added all the new barcode types to the metadata array.
I also added support for iPhone and iPad device.

I also took the liberty of making some code better.

I've tested all the barcode types and general stability of the framework and example project.

Would you like me to submit a Pull Request to add all these features to your Scanner?

**Comment by vadymmarkov** [comment]
Sounds great @chadcummings We would love to see your PR 😉

**Comment by Patchivic** [comment]
I have made the changes using the Xcode converter itself. But I do have 2 errors for below 2 lines in BarcodeScannerController.swift

1) guard metadataObjects != nil && !metadataObjects.isEmpty else { return }
Error : Comparing non-optional value of type '[AVMetadataObject]' to nil always returns true

2) code = code.substring(from: index)
Error : 'substring(from:)' is deprecated: Please use String slicing subscript with a 'partial range from' operator.

**Comment by DavidLari** [comment]
I hope it's not going to be too hard to backport iOS 9.x support into Chad's version because some of us can't just throw away 9% of our users.

**Comment by chadcummings** [comment]
@DavidLari I don't mind fixing what I've done to support iOS 9. I was operating under the assumption that anyone needing a barcode scanner would have abandoned old versions of iOS long ago. I'll make the change to support iOS 9.0 and higher before I submit my PR.

@Patchivic I've already fixed those two errors and figured out why data is no longer read from the camera metadata.

**Comment by chadcummings** [comment]
Is everyone ok with iOS 9.3 as the Deployment Target?
That version will support:
- iPhone 4S and greater
- iPod Touch 5th Gen and greater
- iPad 2 and greater

**Comment by skofgar** [comment]
By supporting iOS 9 you have 98% of all iOS devices, so I think choosing iOS 9.x is a good choice.

https://developer.apple.com/support/app-store/

**Comment by DavidLari** [comment]
Awesome Chad! Thanks!

**Comment by Patchivic** [comment]
@chadcummings can you open a PR for your updated code?

**Comment by chadcummings** [comment]
https://github.com/hyperoslo/BarcodeScanner/pull/64

**Comment by vadymmarkov** [comment]
PR made by @chadcummings was successfully merged and version 3.0.0 is out.
