### ISSUE TITLE
Swift 4 version for CocoaPod is not available

### ISSUE THREAD

**Issue by matin-kaj** [hyperoslo/BarcodeScanner#65]
Can you update cocoaPod to get updated version for `Swift 4`

**Comment by Patchivic** [comment]
As a user, and since the PR is already approved, it will just take some time to update master version. At the time you can check that [link](https://github.com/hyperoslo/BarcodeScanner/tree/f2e4fa3fd32bb9bdfc9259c10ccc7e722e4babc5) for the updated files.

**Comment by vadymmarkov** [comment]
https://github.com/hyperoslo/BarcodeScanner/releases/tag/3.0.0
