### ISSUE TITLE
Swift 3.2 Crash

### ISSUE THREAD

**Issue by fiantinangon** [hyperoslo/BarcodeScanner#66]
Hi, since i update to xcode 9, i have this crash when open scanner : 

'<UILabel: 0x15fe958c0; frame = (0 0; 0 0); userInteractionEnabled = NO; animations = { contentsMultiplyColor=<CABasicAnimation: 0x1c023b100>; }; layer = <_UILabelLayer: 0x1c409d920>> has been added as a subview to <BarcodeScanner.InfoView: 0x15fe948a0; baseClass = UIVisualEffectView; frame = (0 0; 0 0); layer = <CALayer: 0x1c4236300>>. Do not add subviews directly to the visual effect view itself, instead add them to the -contentView.'

-----------------
I fix this issue by changing

 [label, imageView, borderView].forEach {
      self.contentView.addSubview($0)
    }

Should i submit PR for this ?

**Comment by kostapappas** [comment]
pod 'BarcodeScanner', :git => 'https://github.com/hyperoslo/BarcodeScanner.git', :tag => '2.1.2'

for XCode 9, and swift 3.2. No crash after that.
