### ISSUE TITLE
Calling dismiss outside of barcodeScannerDidDismiss, CPU goes to 100+

### ISSUE THREAD

**Issue by eebean2** [hyperoslo/BarcodeScanner#67]
When calling dismiss on the `BarcodeScannerController` outside of `barcodeScannerDidDismiss` delegate method, the iOS device CPU goes to over 100%

**Comment by eebean2** [comment]
Note: workaround is to call `resetWithError()` before, calling `reset()` or not calling anything on the controller before hand does not work.

**Comment by martheli** [comment]
+1 Would be good to get a PR to get this issue resolved without having to call the error reset first.

**Comment by rayfarer** [comment]
Has this issue been addressed yet? Almost unusable because of how much of a load is placed on the CPU.

**Comment by vadymmarkov** [comment]
Please test with v.4.0.0 and let us know if it's still a problem. Now when you dismiss controller capture session will be stopped. Note that you shouldn't keep a reference to `BarcodeScannerViewController` if you want it to be deallocated on dismiss.
