### ISSUE TITLE
Crashes on simulator launch

### ISSUE THREAD

**Issue by jonchui** [hyperoslo/BarcodeScanner#68]
Not a huge issue, but just want to make sure this doesn't happen on production devices  with no camera (are there any? ipod?)

seems this line:
```
  lazy var captureDevice: AVCaptureDevice = AVCaptureDevice.defaultDevice(withMediaType: AVMediaTypeVideo)
```

is causing the `EXC_BAD_ACCESS` error crash when pressing the "Scan" button:

```
fatal error: unexpectedly found nil while unwrapping an Optional value
2017-10-02 10:35:40.653827-1000 BarcodeScannerExample[34615:904682] fatal error: unexpectedly found nil while unwrapping an Optional value
```

**Comment by adle29** [comment]
Anyone has a fix for this?

**Comment by onmyway133** [comment]
@jonchui @adle29 I think it's good to test on real devices, and it make senses to crash if there's no `captureDevice`. If you want to test on simulator, before constructing and showing `BarcodeScanner`, I think you should have a simulator check, and show something else if that is the case. Hope you understand

**Comment by prcodes** [comment]
I have a PR that fixes this here: https://github.com/hyperoslo/BarcodeScanner/pull/77
