### ISSUE TITLE
Cocoapods install failed

### ISSUE THREAD

**Issue by frederic-adda** [hyperoslo/BarcodeScanner#7]
Hi
I tried to install this lib via Cocoapods using the command 

> pod 'BarcodeScanner'

 as explained in the help, but I get the following message error in the Terminal running pod install:

> Unable to find a specification for `BarcodeScanner`

Thanks for your help

**Comment by vadymmarkov** [comment]
Hi @frederic-adda! I just tried to reproduce it by adding `pod 'BarcodeScanner'` in the Podfile and the dependency was successfully resolved. It might be that you have an issue with the pod master repo.

**Comment by onmyway133** [comment]
@frederic-adda you can try `pod repo update` before `pod install`

**Comment by frederic-adda** [comment]
Thanks, worked perfectly!
