### ISSUE TITLE
Updated Version of this library to 3.0.0. Getting errors on compile time.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [hyperoslo/BarcodeScanner#70]
I have just updated all the pods of my project by hitting `pod update` command.
all the libraries are updated to latest version.

The problem is this library has version 2.0.0 (older) which is updated to 3.0.0 (newer).
And getting compile time errors.

I am using latest Xcode Version 9.0 (9A235).

What should I do?

**Comment by onmyway133** [comment]
@Rashesh-Bosamiya Hi, did you set swift version in your project to 4.0 ?
