### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by harrisoftware** [hyperoslo/BarcodeScanner#72]
Any plans to support MSI-PLESSEY?
It is still widely in use.
:)

**Comment by zenangst** [comment]
Hey @harrisoftware, `BarcodeScanner` is built on top of `AVFoundation` and supports all the types that Apple supports. You can see the supported types here: https://developer.apple.com/documentation/avfoundation/avmetadataobject.objecttype

If you only want to support a subset of object types you can change that in `BarcodeScanner.metadata`.
https://github.com/hyperoslo/BarcodeScanner/blob/master/Sources/Config.swift#L76-L91

As far as I can see, `MSI-PLESSEY` is not in the list of supported types.

Hope this helped to clarify the issue.
