### ISSUE TITLE
Controller.dismiss not working

### ISSUE THREAD

**Issue by martheli** [hyperoslo/BarcodeScanner#73]
I have the below set up to dismiss the controller once bar code has been scanned but the controller stays at "Looking for your product..." animation:

```
extension ViewController: BarcodeScannerCodeDelegate {
    
    func barcodeScanner(_ controller: BarcodeScannerController, didCaptureCode code: String, type: String) {
      
        controller.dismiss(animated: true)

    }
}
```

I am running Xcode 9.1 on device with iOS 11.1.

**Comment by michaelbina** [comment]
I'm having this same problem.  How was this resolved?

**Comment by soenkegissel** [comment]
Same here.
