### ISSUE TITLE
iPhoneX layout issue (Close button)

### ISSUE THREAD

**Issue by DavidLari** [hyperoslo/BarcodeScanner#76]
In portrait on iPhoneX, the header view with the close button and title label are too close to the notch. There's very little of the close button that is a tappable target as a result. Looks like it needs to be refactored to use safe areas.

**Comment by prcodes** [comment]
I noticed this as well, I have a PR out here: https://github.com/hyperoslo/BarcodeScanner/pull/77

**Comment by vadymmarkov** [comment]
Fixed in #77
