### ISSUE TITLE
Close button and title not shown in navigationBar on iOS 10 and below

### ISSUE THREAD

**Issue by javialgaba** [hyperoslo/BarcodeScanner#83]
With the latest release (3.0.2), only on iOS 11 the closeButton and title are shown. 

Thanks!

**Comment by onmyway133** [comment]
@javialgaba Thanks for reporting, I will take a look

**Comment by onmyway133** [comment]
@javialgaba Hi, can you check https://github.com/hyperoslo/BarcodeScanner/releases/tag/3.0.3

**Comment by javialgaba** [comment]
It works great. Thanks!
