### ISSUE TITLE
How can I get barcode type?

### ISSUE THREAD

**Issue by oniikal3** [hyperoslo/BarcodeScanner#9]
I see delegate return only code. So How can I get type?

**Comment by inatu** [comment]
Check https://github.com/hyperoslo/BarcodeScanner/blob/master/Sources/BarcodeScannerController.swift#L424-L426, I think the right solution is to fork this repo, and create  modify the `BarcodeScannerCodeDelegate` protocol to return the code type for your own usage, also check this link https://github.com/hyperoslo/BarcodeScanner/blob/master/Sources/Config.swift#L70-L81 for type details.
