### ISSUE TITLE
Hide MessageView

### ISSUE THREAD

**Issue by inkl** [hyperoslo/BarcodeScanner#92]
Hi, how do I hide the entire messageView at the bottom?
I don't need it to be display. Thanks ;-)

**Comment by vadymmarkov** [comment]
@inkl You can try this code to hide it:

```swift
let viewController = BarcodeScannerViewController()
viewController.messageViewController.view.isHidden = true
```

But if you want to see loading animation don't forget to reset it to true at some point, for example in:
```swift
func barcodeScanner(_ controller: BarcodeScannerViewController, didCaptureCode code: String, type: String)
```

**Comment by vadymmarkov** [comment]
Hope it helped :)

**Comment by nikeshakya** [comment]
@vadymmarkov hey bro 
I want to remove messageViewController. How can I do it? 
hiding the view will create a black screen at the bottom. 
It seems like the constraint of camera view is set to footer height which is the height of message view and its blocking the full screen of camera view..
I need to make camera view stretched to the safe area height.
thanks

**Comment by mtet88** [comment]
@nikeshakya "no worries. Done and clear" how? I'm currently having that issue

**Comment by nikeshakya** [comment]
@mtet88 I had to change constraint properties of camera view (bottom constraint to main view) and send message view back with self.view.sendSubView(Back: MessageView)

**Comment by hardikihorizon** [comment]
@nikeshakya  hey can you add a snippet, please
