### ISSUE TITLE
is there anyway to set BarcodeScanner.Info.text in version 4.0.0?

### ISSUE THREAD

**Issue by jenlai1345** [hyperoslo/BarcodeScanner#93]
Hi,

Because I need to localize the app to Chinese. I was able to set the Info text in the older version.
Is there anyway I can customize the texts in the newest version?

Thank you very much for your good work!

   BarcodeScanner.Info.text 
   BarcodeScanner.Info.loadingText 
   BarcodeScanner.Info.notFoundText

**Comment by vadymmarkov** [comment]
Hi @jenlai1345. 

You can copy the following keys to localisable strings file in your app and add translation: `https://github.com/hyperoslo/BarcodeScanner/blob/master/Localization/en.lproj/Localizable.strings`. 

You could also make a PR with Chinese localisation, in the same way it's done for other locales https://github.com/hyperoslo/BarcodeScanner/tree/master/Localization

**Comment by jenlai1345** [comment]
Hi @vadymmarkov 

Thank you for your swift response.
Unfortunately, I need to customize my info text for different types of scenario to instruct the user to scan what types of QRCodes and at other times book barcodes. It seems that using localization file, I can only  have 1 specific INFO text for the localization used.

Thank you very much for your help!

**Comment by vadymmarkov** [comment]
@jenlai1345 Now it should be possible to set your custom text in 4.1.0. Hope it solves your problem.

```swift
viewController.messageViewController.messages.scanningText = "Scanning..."
```

**Comment by jenlai1345** [comment]
Thank you so much @vadymmarkov ! Really appreciate it.
Thank you for your excellent work.
